export enum ErrorCodeQuota {
  QUOTA_EXCEEDED_TRIGGERS_AMOUNT = 'QUOTA_EXCEEDED_TRIGGERS_AMOUNT',
}

enum ErrorCodeDefault {
  INVALID_TYPE = 'INVALID_TYPE',
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  CONFIG_NOT_FOUND = 'CONFIG_NOT_FOUND',
  ENGINE_OPERATION_FAILURE = 'ENGINE_OPERATION_FAILURE',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  EXECUTION_TIMEOUT = 'EXECUTION_TIMEOUT',
  FLOW_INSTANCE_NOT_FOUND = 'INSTANCE_NOT_FOUND',
  INVALID_API_KEY = 'INVALID_API_KEY',
  INVALID_BEARER_TOKEN = 'INVALID_BEARER_TOKEN',
  INVALID_OR_EXPIRED_JWT_TOKEN = 'INVALID_OR_EXPIRED_JWT_TOKEN',
  JOB_REMOVAL_FAILURE = 'JOB_REMOVAL_FAILURE',
  JOB_FAILURE = 'JOB_FAILURE',
  JOB_INVALID = 'JOB_INVALID',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  SYSTEM_ENV_INVALID = 'SYSTEM_PROP_INVALID',
  SYSTEM_ENV_NOT_DEFINED = 'SYSTEM_PROP_NOT_DEFINED',
  CUSTOMER_IS_INACTIVE = 'CUSTOMER_IS_INACTIVE',
  VALIDATION = 'VALIDATION',
  DATABASE_INTERNAL = 'DATABASE_INTERNAL',
  INTERNAL_SERVER = 'INTERNAL_SERVER',
  HTTP = 'HTTP',
  WEB_SOCKET_ERROR = 'WEB_SOCKET_ERROR',
  FEATURE_NOT_IMPLEMENTED = 'FEATURE_NOT_IMPLEMENTED',
}

/* Merge Error enums */
export const ErrorCode = { ...ErrorCodeDefault, ...ErrorCodeQuota }
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
